# .goreleaser.yaml
version: 2

project_name: introspection

builds:
  - id: library
    binary: introspection
    # We are a library, so we don't compile binaries.
    # However, goreleaser requires a 'builds' section to be valid.
    # We set a dummy target (linux/amd64) and 'skip: true' to satisfy this
    # without actually building anything.
    goos: [linux]
    goarch: [amd64]
    skip: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
